### ISSUE TITLE
[RLStats] [p]rlstats erroring out for PS4 players

### ISSUE THREAD

**Issue by PredaaA** [jack1142/JackCogs#21]
This error is raised when using `[p]rlstats` followed by a PS4 player name.
Here is a player list where it is erroring out for me: SandMonkeyBois24, evo, Elite_BFM.
```py
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/cogs/CogManager/cogs/rlstats/rlstats.py", line 382, in rlsports
    await self._rlstats_logic(ctx, self.extramodes_template, playlists, player_id)
  File "/data/cogs/CogManager/cogs/rlstats/rlstats.py", line 448, in _rlstats_logic
    fp = await self._run_in_executor(
  File "/data/cogs/CogManager/cogs/rlstats/rlstats.py", line 207, in _run_in_executor
    return await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/cogs/CogManager/cogs/rlstats/rlstats.py", line 345, in _generate_image
    result = template.generate_image(player, playlists)
  File "/data/cogs/CogManager/cogs/rlstats/image.py", line 69, in generate_image
    return RLStatsImage(self, player, playlists)
  File "/data/cogs/CogManager/cogs/rlstats/image.py", line 139, in __init__
    self._generate_image()
  File "/data/cogs/CogManager/cogs/rlstats/image.py", line 147, in _generate_image
    self._draw_username()
  File "/data/cogs/CogManager/cogs/rlstats/image.py", line 169, in _draw_username
    w, h = font.getsize(self.player.user_name)
  File "/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 262, in getsize
    size, offset = self.font.getsize(text, direction, features, language)
TypeError: expected string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 824, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: expected string
```

**Comment by Jackenmen** [comment]
The fix required a new version of `rlapi` package, so bot restart might be required.
