### ISSUE TITLE
RLstats Failed to load packages in Red

### ISSUE THREAD

**Issue by SickProdigy** [jack1142/JackCogs#58]
Hello, getting Failed to load package for rlstats.

My logs is looking like this

```
[2023-08-06 23:49:28] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/home/userid/redenv/lib/python3.10/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/home/userid/redenv/lib/python3.10/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
  File "/home/userid/Documents/python-bots/red-discord-cog/cogs/CogManager/cogs/rlstats/__init__.py", line 42, in setup
    await bot.add_cog(cog)
  File "/home/userid/redenv/lib/python3.10/site-packages/redbot/core/bot.py", line 1909, in add_cog
    await super().add_cog(cog, guild=guild, guilds=guilds)
  File "/home/userid/redenv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 783, in add_cog
    cog = await cog._inject(self, override=override, guild=guild, guilds=guilds)
  File "/home/userid/redenv/lib/python3.10/site-packages/discord/ext/commands/cog.py", line 684, in _inject
    await maybe_coroutine(self.cog_load)
  File "/home/userid/redenv/lib/python3.10/site-packages/discord/utils.py", line 693, in maybe_coroutine
    return await value
  File "/home/userid/Documents/python-bots/red-discord-cog/cogs/CogManager/cogs/rlstats/rlstats.py", line 227, in cog_load
    tier_breakdown = await get_tier_breakdown(self.rlapi_client)
  File "/home/userid/Documents/python-bots/red-discord-cog/cogs/Downloader/lib/rlapi/ext/tier_breakdown/trackernetwork.py", line 55, in get_tier_breakdown
    result = await _get_playlist_breakdown(client, playlist_id)
  File "/home/userid/Documents/python-bots/red-discord-cog/cogs/Downloader/lib/rlapi/ext/tier_breakdown/trackernetwork.py", line 79, in _get_playlist_breakdown
    text: Dict[str, Any] = await client._request(url)
  File "/home/userid/Documents/python-bots/red-discord-cog/cogs/Downloader/lib/rlapi/client.py", line 194, in _request
    raise errors.HTTPException(resp, data)
rlapi.errors.HTTPException: Forbidden (status code: 403): 
<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
    <meta name="msapplication-navbutton-color" content="#080808">
    <meta name="theme-color" content="#080808">
    <meta name="google-site-verification" content="spvb9FJmktijuUuNiAoicMXyQg8X8cuqtQSz_A-LNI8" />
    <meta name="google-play-app" content="app-id=network.tracker.app">
    <meta name="apple-itunes-app" content="app-id=1287696482">

    <title>You've been blocked</title>
```

Going to take a further look, was just wondering if anyone had a quick fix or should I just try a vpn? Figured I'd start an issue for now.

**Comment by Jackenmen** [comment]
I removed the related functionality, it's not an essential feature and it seems that Tracker Network does not like this kind of usage. You should be able to load the cog now.
